### ISSUE TITLE
Results not displaying

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-provider-elasticsearch#3]
I am unable to get a feature set to display on an AGOL map viewer. 

I have the service up and running  and it is populating the console.log ("Features "" Found) with the correct number of records.  However the features never make it back to a feature set and into AGOL

**Comment by dhatcher** [comment]
Can you see what the results look like coming into the web map using developer tools on chrome or similar?

**Comment by rgwozdz** [comment]
@keithfraley - if you can use fiddler of dev tools to get the request's GET query parameters or POST body, that can be helpful for identifying the issue.

**Comment by keithfraley** [comment]
![image](https://user-images.githubusercontent.com/3977556/38508400-bbfec840-3be4-11e8-83f3-cb4b9cd87461.png)

**Comment by keithfraley** [comment]
The data is coming across except for the geometries

**Comment by keithfraley** [comment]
![image](https://user-images.githubusercontent.com/3977556/38508881-f5cccd32-3be5-11e8-9b21-ea74ec515848.png)

**Comment by keithfraley** [comment]
notice the geometry field is coming back as type string

**Comment by rgwozdz** [comment]
@keithfraley - this is indeed strange.  The `fields` array usually just holds a features attributes, not it's geometry.  Each feature usually has an `attributes` object that contains the properties listed in the fields array, and then a separate `geometry` object (so long as the `returnGeometry` option doesn't equal false).  I'm not sure why your `geometry` is getting stored in `attributes`.  As far as it being typed as a string, that likely happens because there are only these [options](https://github.com/koopjs/FeatureServer/blob/3a2aaa45d3a0e8937281596a0e1c7baba59fcccc/src/field/field-map.js) for field types, and perhaps your `geometry` value arrives as a JSON string.

**Comment by dhatcher** [comment]
Is your geometry field typed as 'geo_point' in elastic?

**Comment by keithfraley** [comment]
sorry that was for a table query

![image](https://user-images.githubusercontent.com/3977556/38513000-85a2466a-3bf2-11e8-8629-208d90edc4f7.png)

**Comment by keithfraley** [comment]
it looks like the data is in wgs 84 and not web mercator?

**Comment by dhatcher** [comment]
Yep the data is stored as wgs84 in Elastic.  The arcgis map client should do the conversion for you though when it gets the result.  I think your issue is possibly related to the ObjectID.  Are your _id values coming from the elastic documents GUIDS?

**Comment by keithfraley** [comment]
Yes

**Comment by dhatcher** [comment]
I just made an update, can you get latest and see if you get better results?

**Comment by dhatcher** [comment]
Depending on how you first got the project a download or a pull.

**Comment by dhatcher** [comment]
Looking closer at your screen share I'm not sure that's going to solve all of your problems.  Do you have the geometry field listed in your return fields?  It shouldn't be there if so.  I don't know if that would cause the geometry to be empty like it is but it will confuse the web map because it has an array value.

**Comment by keithfraley** [comment]
Awesome, thanks I will take a look

**Comment by keithfraley** [comment]
ok, that latest update fixed the issue of display. Awesome!!

I am however not able to use the filters on time fields

(node:6389) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Syntax error found near Identifier (WHERE Clause)

Also the table is loading any of the data.

**Comment by dhatcher** [comment]
can you make a new issue for the time fields in the where clause?  It's not been tested with time fields yet.

Did you remove the geometry field from your return fields?  If not that could be causing the table to fail.
